### PR TITLE
#1728 - Fix List Number Query

### LINKED ISSUE #1728: Fix list number querry
Queries using number parameters are not working
`makeRequestOnPosts("GET", "contacts", { "my_number_field": { "equality": ">", "number": 30}})`
Should work, but return an empty list. 

Should match:
https://developers.disciple.tools/theme-core/api-posts/list-query#number

Make sure to create phpunit tests

### PR DESCRIPTION
**Pull request by kodinkat**
fixes #1728

### CODE REVIEW

File: dt-posts/posts.php [hunk 1]
```diff
@@ -949,8 +949,11 @@ public static function fields_to_sql( $post_type, $query_array, $operator = "AND
                              */
                             $equality = '=';
                             $value = is_numeric( $query_value ) ? esc_sql( $query_value ) : [];
-                            if ( isset( $query_value['operator'] ) ){
-                                $equality = esc_sql( $query_value['operator'] );
+
+                            foreach ( [ 'operator', 'equality' ] as $term ) {
```
Comment (corsacca) [inline dt-posts/posts.php:953]: @kodinkat why use both here?
